### ISSUE TITLE
Error loading SublimeHg

### ISSUE THREAD

**Issue by abv** [SublimeText/SublimeHg#4]
Hi, I'm new to Sublime. I keep seeing this error in the console when starting up Sublime & can't get SublimeHg to work :(

```
Reloading plugin /Users/adam/Library/Application Support/Sublime Text 2/Packages/SublimeHg/hg_commands.py
Reloading plugin /Users/adam/Library/Application Support/Sublime Text 2/Packages/SublimeHg/setup.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 57, in reload_plugin
  File "./setup.py", line 590, in <module>
    url='sublimetext.info',
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/core.py", line 106, in setup
    attrs['script_name'] = os.path.basename(sys.argv[0])
AttributeError: 'module' object has no attribute 'argv'
Reloading plugin /Users/adam/Library/Application Support/Sublime Text 2/Packages/SublimeHg/sublime_hg.py
```

**Comment by abv** [comment]
I got a little further in the install process, but now see this when I try to run hg status from within Sublime.

```
Traceback (most recent call last):
  File "./sublime_hg.py", line 223, in on_done
  File "./sublime_hg.py", line 82, in __init__
  File "./sublime_hg.py", line 92, in start_server
  File "./hglib/__init__.py", line 9, in open
  File "./hglib/client.py", line 27, in __init__
  File "./hglib/client.py", line 33, in _readhello
AssertionError
```

**Comment by guillermooo** [comment]
This seems to be a problem with the included hglib library, and not sublime_hg itself.

**Comment by abv** [comment]
In case anyone else runs into this issue, the problem was that I was using an older version of Mercurial (1.8). I just upgraded to the latest version and everything works great.
