### ISSUE TITLE
Unpack error, cannot run any commands

### ISSUE THREAD

**Issue by keyo** [SublimeText/SublimeHg#9]
```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 344, in run_
  File ".\sublime_hg.py", line 161, in run
  File ".\sublime_hg.py", line 174, in on_done
  File ".\sublime_hg.py", line 55, in select_server
  File ".\sublime_hg.py", line 41, in start_server
  File ".\shglib\client.py", line 38, in __init__
  File ".\shglib\client.py", line 54, in read_greeting
  File ".\shglib\client.py", line 46, in read_channel
struct.error: unpack requires a string argument of length 5
```

Windows 7 (can run with cmd>hg), Mercurial 2.1.1, SublimeText 2 build 2181

**Comment by guillermooo** [comment]
How are you running the plugin ("console", quick panel)? What Mercurial dist do you have installed (TortoiseHg, plain Mercurial)?

**Comment by keyo** [comment]
TortoiseHg (at C:\Program Files\TortoiseHg\hg.exe), although it is in the system paths, so just running 'hg' works from the windows shell.

I've tried both Menu and CLI. If I use any command, annotate, help, help add, branch etc I get errors in the console pane. There are no errors in the plugin user interfaces, it just appears to do nothing.

Thanks for the quick response.

**Comment by guillermooo** [comment]
It seems the command server will not work if unsupported extensions are enabled. Can you please disable all extensions in _%USERPROFILE%\.hgrc_ and see whether it works after that?
